accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('', views.index, name="index"),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('password/', views.password_change, name='password_change'),
    path('<int:user_pk>/', views.detail, name='detail'),    # 프로필
    path('<int:user_pk>/delete/', views.delete, name='delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/following/', views.following, name='following'),
    path('<int:user_pk>/follower/', views.follower, name='follower'),

]

moviebuddy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movies_index, name='movies_index'),
    path('genres/', views.genres_index, name="genres_index"),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('<int:movie_pk>/ratings/<int:rating_pk>/update/', views.rating_update, name='rating_update'),
    path('<int:movie_pk>/ratings/<int:rating_pk>/delete/', views.rating_delete, name='rating_delete'),
    path('<int:movie_pk>/ratings/new/', views.create_rating, name='create_rating'),
    path('myfavorite/', views.myfavorite, name='myfavorite'),
    path('genres/', views.genres_list, name='genres_list'),
    path('actors/', views.actors_list),
    path('api/genres/', views.genres_list, name="genres_list"),
    path('api/genres/<int:pk>/', views.genres_detail, name="genres_detail"),
    path('api/movies/<int:pk>/', views.movies_detail, name="movies_detail"),
    
]

movies/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=150)
    genre_id = models.TextField()

    def __str__(self):
        return self.name

class Movie(models.Model):
    adult = models.TextField()
    budget = models.TextField()
    genres = models.TextField()
    original_title = models.TextField()
    overview = models.TextField() # description
    popularity = models.TextField() # audience
    poster_path = models.TextField() # post_url
    release_date = models.TextField()
    revenue = models.TextField()
    runtime = models.TextField()
    tagline = models.TextField()
    title = models.CharField(max_length=150)
    vote_average = models.FloatField()
    actor_1 = models.TextField()
    actor_2 = models.TextField()
    actor_3 = models.TextField()
    actor_4 = models.TextField()
    actor_5 = models.TextField()
    director = models.CharField(max_length=45)
    file_path_1 = models.TextField()
    file_path_2 = models.TextField()
    file_path_3 = models.TextField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_movies")

    def __str__(self):
        return self.title

class Actor(models.Model):
    actor_id = models.TextField()
    actor_name = models.TextField()

    def __str__(self):
        return self.actor_name


class Rating(models.Model): # Review
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    comment = models.TextField()
    score = models.IntegerField(default=1,
                validators=[
                    MaxValueValidator(10),
                    MinValueValidator(1)
            ])

            
    def __str__(self):
        return self.comment

movies/forms.py
from django import forms
from .models import Rating

class RatingForm(forms.ModelForm):
    comment = forms.CharField(max_length=50)
    class Meta:
        model = Rating
        SCORE = ((1,1),(2,2),(3,3),(4,4),(5,5),(6,6),(7,7),(8,8),(9,9),(10,10),)
        fields = ['score', 'comment',]
        
        widgets  = {
            'score': forms.Select(choices=SCORE)
        }

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Genre, Movie, Rating, Actor
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .forms import RatingForm
from django.contrib import messages
from django.http import HttpResponseForbidden, HttpResponse, JsonResponse

from django.conf import settings
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import GenreSerializer, MovieSerializer, RatingSerializer, ActorSerializer
from django.contrib.auth import get_user_model
import random

# Create your views here.
def movies_index(request):
    movies = Movie.objects.exclude(poster_path=0)
    movies_popular = Movie.objects.order_by('id')[0:20]
    movies_vote = Movie.objects.order_by('-vote_average')[0:20]
    genres = Genre.objects.all()
    favorite_movies = ''
    recommends = will_likes = []
    cnt = 4
    if request.user.is_authenticated:
        people = request.user.followers.all()
        favorite_movies = request.user.like_movies.all()
        for person in people:
            ratings = person.rating_set.filter(score__gt=6)
            for rate in ratings:
                recommends.append(rate.movie)
            for favorite in favorite_movies:
                if not favorite in recommends:
                    recommends.append(favorite)
            if len(recommends) < 4: cnt = len(recommends)
            will_likes = random.sample(recommends, cnt)

    keyword = request.GET.get('keyword', '')
    if keyword:
        movies = movies.filter(title__icontains=keyword)
        context = {
            'keyword': keyword,
            'movies_popular' : None,
            'movies_vote' : None,
            'movies': movies,
            'genres' : genres,
        }
    else:
        context = {
            'movies_popular' : movies_popular,
            'movies_vote' : movies_vote,
            'movies': None,
            'genres' : genres,
            'will_likes': will_likes,
            'favorite_movies': favorite_movies,
        }
    return render(request, 'movies/movies_index.html', context)
    
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    genre = Genre.objects.filter(genre_id=movie.genres)
    ratings = movie.rating_set.all()
    actors = []
    if movie.actor_1: actors.append(Actor.objects.filter(actor_id=movie.actor_1)[0].actor_name)
    if movie.actor_2: actors.append(Actor.objects.filter(actor_id=movie.actor_2)[0].actor_name)
    if movie.actor_3: actors.append(Actor.objects.filter(actor_id=movie.actor_3)[0].actor_name)
    if movie.actor_4: actors.append(Actor.objects.filter(actor_id=movie.actor_4)[0].actor_name)
    if movie.actor_5: actors.append(Actor.objects.filter(actor_id=movie.actor_5)[0].actor_name)
    rating_form = RatingForm()
    context = {
        'genre_name' : genre[0],
        'movie': movie,
        'actors' : actors,
        'ratings': ratings,
        'rating_form': rating_form
    }
    return render(request, 'movies/movies_detail.html', context)

def genres_index(request):
    genre = get_object_or_404(Genre, name=request.GET.get('name'))
    movies = Movie.objects.order_by('id').filter(genres=genre.genre_id).exclude(overview=0)[0:50]
    return render(request, 'movies/genre.html', {'genre': genre, 'movies': movies})

@api_view(["GET"])
def movies_list(request):
    movies = Movie.objects.all()
    serializer = MovieSerializer(movies, many=True)
    return Response(serializer.data)

@api_view(["GET"])
def genres_list(request):
    genres = Genre.objects.all()
    serializer = GenreSerializer(genres, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def actors_list(request):
    actors = Actor.objects.all()
    serializer = ActorSerializer(actors, many=True)
    return Response(serializer.data)

@api_view(["GET"])
def genres_detail(request, pk):
    genre = get_object_or_404(Genre, pk=pk)
    serializer = GenreSerializer(genre)
    return Response(serializer.data)

@api_view(["GET"])
def movies_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    serializer = MovieSerializer(movie)
    return Response(serializer.data)

@require_POST
@login_required
def create_rating(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if len(movie.rating_set.filter(user_id = request.user.id)) == 0:
        rating_form = RatingForm(request.POST)
        if rating_form.is_valid():
            rating = rating_form.save(commit=False)
            rating.user = request.user
            rating.movie_id = movie_pk
            rating.save()
    else:
        messages.success(request, '이미 등록한 평점이 있습니다.')
    return redirect('movies:detail', movie_pk)

@login_required
def rating_update(request, movie_pk, rating_pk):
    rating = get_object_or_404(Rating, pk=rating_pk)
    if rating.user != request.user:
        return redirect('movies:detail', movie_pk)

    if request.method == 'POST':
        rating_form = RatingForm(request.POST, instance=rating)
        if rating_form.is_valid():
            rating_form.save()
            return redirect('movies:detail', movie_pk)
    else:
        rating_form = RatingForm(instance=rating)
    context = {
        'rating_form':rating_form,
    }
    return render(request, 'movies/form.html', context)

@login_required
def rating_delete(request, movie_pk, rating_pk):
    rating = get_object_or_404(Rating, pk=rating_pk)
    if request.method == 'POST':
        rating.delete()
        messages.warning(request, '리뷰가 삭제되었습니다.')
    return redirect('movies:detail', movie_pk)

@login_required
def like(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    
    # 좋아요를 누른적이 있다면?
    is_liked = True
    if movie in request.user.like_movies.all():
        # 좋아요 취소 로직
        request.user.like_movies.remove(movie)
        is_liked = False
    # 아니면
    else:
        # 좋아요 로직
        request.user.like_movies.add(movie)
        is_liked = True
    return JsonResponse({'is_liked': is_liked, 'likers': movie.like_users.count()})

@login_required
def myfavorite(request):
    movies = request.user.like_movies.all()
    context = {
        'movies' : movies    
    }
    return render(request, 'movies/myfavorite.html', context)

movies/templates/movies/genre.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load humanize %}
{% load bootstrap4 %}
{% block app %}
<section id="genre">
    <section class="hero is-black">
        <div class="hero-body">
            <div class="container">
                <div>
                    <span class="tag is-white" v-for="genre in genreList"
                        :class="{ 'is-info': genre.name === selectedGenre }">
                        <a :href=`/movies/genres/?name=${genre.name}`> <button type="button"
                            class="btn btn-light mt-2">[[ genre.name ]]</button>&nbsp;
                        </a>
                    </span>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <hr class="border-white">
            <br>
            <h1 class="title is-2" v-text="selectedGenre"
                style="font-family: 'Do Hyeon','sans-serif'; font-weight: 500; font-size: 55px"></h1>
            <div class="columns is-multiline is-variable is-5" style="padding-left: 1rem; padding-right: 1rem;">
                <div class="column is-one-third" style="margin-bottom: 2rem;">
                    {% for movie in movies %}
                    <table class="" style="border-radius: 10px; background-color: rgb(61, 58, 58, 20);">
                        <thead>
                            <tr>
                                <th>
                                    <a href="/movies/{{movie.pk}}/"><img
                                            src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}"
                                            alt="{{ movie.title }}"
                                            style="border-radius: 10px; width:300px; margin-right: 20px;"></a></th>
                                <th style="margin-left: 30px; text-align: center;">
                                    <h1 style="color:rgb(255, 255, 255)">{{ movie.title }}</h1>

                                    {% if 8 <= movie.vote_average and movie.vote_average < 10 %}
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    {% elif 6 <= movie.vote_average and movie.vote_average < 8 %}
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    {% elif 4 <= movie.vote_average and movie.vote_average < 6 %}
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    {% elif 2 <= movie.vote_average and movie.vote_average < 4 %}
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    {% else %}
                                    <i class="fas fa-star fa-spin" style="color:yellow"></i>
                                    {% endif %}
                                    <h6 style="color:rgb(61, 58, 58)">{{ movie.vote_average }}</h6>
                                    <hr>
                                    <br><br><br>
                                    <div
                                        style="text-align:left; font-weight: normal; margin-left: 30px; margin-right: 40px;">
                                        <p style="color:rgb(255, 255, 255)">{{ movie.overview }}</p>
                                        <hr>
                                </th><br><br>

                </div>
                </tr>
                </thead>
                </table>
                {% endfor %}
            </div>
        </div>
        </div>
        <br><br>
    </section>
</section>
{% endblock %}

{% block script %}
<script>
    const passedGenre = '{{genre.name}}'
    const genre = new Vue({
        el: '#genre',
        delimiters: ['[[', ']]'],
        data: {
            movies: [],
            selectedGenre: passedGenre,
            genreList: [],
            genres: [],
        },
        created() {
            axios.get("{% url 'movies:genres_list' %}")
                .then(res => {
                    this.genres = res.data;
                    res.data.forEach(genre => this.genreList.push({
                        id: genre.id,
                        name: genre.name
                    }));
                });
            let url = "{% url 'movies:genres_detail' genre.id %}";
            axios.get(url)
                .then(res => this.movies = res.data.movies);
            console.log(this.movies)
        }
    })
</script>
{% endblock %}

movies/templates/movies/movies_detail.html
{% extends 'accounts/base.html' %}
{% load bootstrap4 %}
{% block app %}
<table>
  <thead>
    <!-- table head!!!! 코드 바뀌는 거는 아니고 의미상 묶어준것-->
    <tr>
      <!-- table row(행) -->
      <th></th> <!-- table header -->
      <th>
        <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt="{{ movie.title }}"
          style="width:450px; margin-right: 20px;"></th>
      <th style="margin-left: 30px; text-align: center;">
        <h1>{{ movie.title }}</h1>

        {% if 8 <= movie.vote_average and movie.vote_average < 10 %}
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        {% elif 6 <= movie.vote_average and movie.vote_average < 8 %}
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        {% elif 4 <= movie.vote_average and movie.vote_average < 6 %}
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        {% elif 2 <= movie.vote_average and movie.vote_average < 4 %}
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        {% else %}
        <i class="fas fa-star fa-spin" style="color:yellow"></i>
        {% endif %}
        <h6>{{ movie.vote_average }}</h6>
        <hr>
        <br><br><br>
        <div style="text-align:left; font-weight: normal; margin-left: 30px;">
          <h6>감독&nbsp;&nbsp;&nbsp;&nbsp; <a href="#">{{ movie.director }}</a></h6>
          <h6>
            출연&nbsp;&nbsp;&nbsp;&nbsp;
            {% for actor in actors %}
            {{ actor }}, &nbsp;
            {% endfor %}
          </h6>
          <h6>개요&nbsp;&nbsp;&nbsp;&nbsp;
            {{ genre_name }}&nbsp;&nbsp;|&nbsp;&nbsp;

            {{ movie.runtime }}분&nbsp;&nbsp;|&nbsp;&nbsp;
            개봉일자 : {{ movie.release_date }}&nbsp;&nbsp;&nbsp;&nbsp;
          </h6><br><br>
          <p>{{ movie.overview }}</p>
          <br>
          <a href='https://www.youtube.com/results?search_query={{movie.title}} +예고편'>
            <div class="favorite-box d-inline" style="color: red; font-family:'Font Awesome 5 Pro';">예고편</div>
          </a>

          {% if user.is_authenticated %}
          <div class="favorite-box d-inline" id="like-btn" data-id="{{movie.id}}">
            {% if user in movie.like_users.all %}
            <i class="fas fa-check-circle animated"> 내가 찜한 영화</i>
            {% else %}
            <i class="far fa-check-circle animated"> 내가 찜한 영화</i>
            {% endif %}
          </div>
          {% endif %}
          <hr>
      </th><br>
      <br><br><br>

      </div>
    </tr>
  </thead>
</table>
<br>
<br>
<a href="{% url 'movies:movies_index' %}">BACK</a>
<hr class="bg-light">
<br>

{% for rating in ratings %}
<h5><a href="{% url 'accounts:detail' rating.user.pk %}">{{ rating.user.username }}</a>
  {% if 8 < rating.score and rating.score <= 10 %}
  <i class="fas fa-star" style="color:yellow"></i>
  <i class="fas fa-star" style="color:yellow"></i>
  <i class="fas fa-star" style="color:yellow"></i>
  <i class="fas fa-star" style="color:yellow"></i>
  <i class="fas fa-star" style="color:yellow"></i>
  {% elif 6 < rating.score and rating.score <= 8 %}
  <i class="fas fa-star" style="color:yellow"></i>
  <i class="fas fa-star" style="color:yellow"></i>
  <i class="fas fa-star" style="color:yellow"></i>
  <i class="fas fa-star" style="color:yellow"></i>
  {% elif 4 < rating.score and rating.score <= 6 %}
  <i class="fas fa-star" style="color:yellow"></i>
  <i class="fas fa-star" style="color:yellow"></i>
  <i class="fas fa-star" style="color:yellow"></i>
  {% elif 2 < rating.score and rating.score <= 4 %}
  <i class="fas fa-star" style="color:yellow"></i>
  <i class="fas fa-star" style="color:yellow"></i>
  {% else %}
  <i class="fas fa-star" style="color:yellow"></i>
  {% endif %}
  {{ rating.score }}
  {% if rating.user == request.user %}
  <form action="{% url 'movies:rating_update' movie.pk rating.pk %}" method='GET' class="d-inline">
    <input type="submit" value="EDIT" class='btn text-info' />
  </form>
  <form action="{% url 'movies:rating_delete' movie.pk rating.pk %}" method='POST' class="d-inline">
    {% csrf_token %}
    <input type="submit" value="DELETE" class='btn text-danger' />
  </form>
  {% endif %}
</h5>
{{ rating.comment }}

<hr class="bg-light">
{% empty %}
평점이 없습니다.
<hr class="bg-light">
{% endfor %}


{% if user.is_authenticated %}
<form action="{% url 'movies:create_rating' movie.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form rating_form %}
  <!-- <button type="submit">확인</button> -->
  <div class="d-flex justify-content-end">
    <input type="submit" value="작성하기" class="btn btn-dark" />
  </div>
</form>
{% endif %}


<br><br><br><br>
<script>
  const likeButton = document.querySelector('#like-btn')
  likeButton.addEventListener('click', function (event) {
    console.log(this)
    axios.get(`/movies/${this.dataset.id}/like/`)
      .then(response => {
        console.log(response)
        console.log(event.target)
        const likers = document.querySelector('#like-count')
        if (response.data.is_liked) {
          this.children[0].classList.remove('far')
          this.children[0].classList.add('fas')
        } else {
          this.children[0].classList.remove('fas')
          this.children[0].classList.add('far')
        }
        likers.innerText = response.data.likers
      })
  })
</script>
<script>
  const likeButton = document.querySelector('#like-btn')
  likeButton.addEventListener('click', function (event) {
    console.log(this)
    axios.get(`/movies/${this.dataset.id}/like/`)
      .then(response => {
        console.log(response)
        console.log(event.target)
        const likers = document.querySelector('#like-count')
        if (response.data.is_liked) {
          this.children[0].classList.remove('far')
          this.children[0].classList.add('fas')
        } else {
          this.children[0].classList.remove('fas')
          this.children[0].classList.add('far')
        }
        likers.innerText = response.data.likers
      })
  })
</script>
{% endblock %}

movies/templates/movies/movies_index.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block app %}

{% if not movies_popular and not movies_vote.count %}
<i class="fas fa-video fa-2x" style="color: #fff; margin-bottom: 0.7rem;"></i>
<h1>{{keyword}} 검색 결과 총 {{movies.count}} 개</h1>
{% for movie in movies %}
<a href="{% url 'movies:detail' movie.pk %}">
    <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt="{{ movie.title }}" style="width:24%;">
</a>
{% empty %}
<h2 style="text-align: center;">등록된 영화가 없습니다.</h2>
{% endfor %}
<div style="padding-top: 4rem; padding-bottom: 5rem;">
        <section class="section" style="padding-bottom: 10rem;">
            <div class="container has-text-centered">
                <i class="fas fa-video fa-2x" style="color: #fff; margin-bottom: 0.7rem;"></i>
                <h1>장르별 영화</h1>
            </div>
            {% include 'movies/_genre-cards.html' %}
        </section>
    </div>
{% else %}
<div>
        <section class="section" style="padding-bottom: 3rem;">
            <div class="container has-text-centered">
                <i class="fas fa-video fa-2x" style="color: #fff; margin-bottom: 0.7rem;"></i>
                <h1>장르별 영화</h1>
            </div>
            {% include 'movies/_genre-cards.html' %}
        </section>
    </div>
{% if user.is_authenticated %}
{% if favorite_movies %}
<i class="fas fa-video fa-2x" style="color: #fff; margin-bottom: 0.7rem;"></i>
<h1>내가 찜한 영화들</h1>
<div class="swiper-container">
    <div class="swiper-wrapper">
        {% for favorite_movie in favorite_movies %}
        <div class="swiper-slide">
            <a href="{% url 'movies:detail' favorite_movie.pk %}">
                <img src="https://image.tmdb.org/t/p/w500/{{ favorite_movie.poster_path }}"
                    alt="{{ favorite_movie.title }}" style="width:280px;">
            </a>
        </div>
        {% endfor %}
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>
<br><br><br>
{% endif %}
{% if will_likes %}
<i class="fas fa-video fa-2x" style="color: #fff; margin-bottom: 0.7rem;"></i>
<h1>{{request.user}}님의 취향저격 베스트 영화</h1>
<div class="swiper-container">
    <div class="swiper-wrapper">
        {% for will_like in will_likes %}
        <div class="swiper-slide">
            <a href="{% url 'movies:detail' will_like.pk %}">
                <img src="https://image.tmdb.org/t/p/w500/{{ will_like.poster_path }}" alt="{{ will_like.title }}"
                    style="width:270px;">
            </a>
        </div>
        {% endfor %}
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>
<br><br><br>
{% endif %}
{% endif %}
<i class="fas fa-video fa-2x" style="color: #fff; margin-bottom: 0.7rem;"></i>
<h1>MovieBuddy 인기 영화</h1>
<div class="swiper-container">
    <div class="swiper-wrapper">
        {% for movie in movies_popular %}
        <div class="swiper-slide">
            <a href="{% url 'movies:detail' movie.pk %}">
                <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt="{{ movie.title }}"
                    style="width:270px;">
            </a>
        </div>
        {% endfor %}
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>
<br><br><br>
<i class="fas fa-video fa-2x" style="color: #fff; margin-bottom: 0.7rem;"></i>
<h1>MovieBuddy 평점순 영화</h1>
<div class="swiper-container">
    <div class="swiper-wrapper">
        {% for movie in movies_vote %}
        <div class="swiper-slide">
            <a href="{% url 'movies:detail' movie.pk %}">
                <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt="{{ movie.title }}"
                    style="width:270px;">
            </a>
        </div>
        {% empty %}
        <p>등록된 영화가 없습니다.</p>
        {% endfor %}
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>
{% endif %}
<br><br><br>

{% endblock %}

{% block script %}
<script>
    const home = new Vue({
        el: '#app',
        delimiters: ['[[', ']]'],
        data: {
            genreCards: [{
                    name: '로맨스',
                    url: "https://static.standard.co.uk/s3fs-public/thumbnails/image/2013/09/06/08/About-Time.jpg?w968"
                },
                {
                    name: 'SF',
                    url: "https://img.newatlas.com/sci-fi-2019-film-tv-4.jpg?auto=format%2Ccompress&dpr=2&fit=max&q=40&w=1000&s=8b98b9bb2888a580ae1f82a4dc231d06"
                },
                {
                    name: '음악',
                    url: 'http://archivenew.vop.co.kr/images/cdcfc3e484a1b92ecab31ba7e4109c20/2017-03/30022242_1.jpg'
                },
                {
                    name: '가족',
                    url: 'https://img3.daumcdn.net/thumb/R658x0.q70/?fname=https://t1.daumcdn.net/news/201805/31/MOVIERISING/20180531194413853a9zs.jpeg'
                },
                {
                    name: '액션',
                    url: 'http://image.cine21.com/resize/cine21/still/2008/0716/M0020025_pl2_66204[W680-].jpg'
                },
                {
                    name: '판타지',
                    url: 'http://cdn.eyesmag.com/wp-content/uploads/2019/04/15150031/marvle-avengers-endgame-movie-kakaopage-main.jpg'
                },
            ]
        },
        methods: {
            getGenreUrl: function (genreCard) {
                return "{% url 'movies:genres_index'%}" + `?name=${genreCard.name}`
            },
        }
    })
</script>
<script src="{% static 'js/3d.js' %}"></script>
{% endblock %}