accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('', views.index, name="index"),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('password/', views.password_change, name='password_change'),
    path('<int:user_pk>/', views.detail, name='detail'),    # 프로필
    path('<int:user_pk>/delete/', views.delete, name='delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/following/', views.following, name='following'),
    path('<int:user_pk>/follower/', views.follower, name='follower'),

]

moviebuddy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movies_index, name='movies_index'),
    path('genres/', views.genres_index, name="genres_index"),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('<int:movie_pk>/ratings/<int:rating_pk>/update/', views.rating_update, name='rating_update'),
    path('<int:movie_pk>/ratings/<int:rating_pk>/delete/', views.rating_delete, name='rating_delete'),
    path('<int:movie_pk>/ratings/new/', views.create_rating, name='create_rating'),
    path('myfavorite/', views.myfavorite, name='myfavorite'),
    path('genres/', views.genres_list, name='genres_list'),
    path('actors/', views.actors_list),
    path('api/genres/', views.genres_list, name="genres_list"),
    path('api/genres/<int:pk>/', views.genres_detail, name="genres_detail"),
    path('api/movies/<int:pk>/', views.movies_detail, name="movies_detail"),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings', blank=True)
    

movies/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=150)
    genre_id = models.TextField()

    def __str__(self):
        return self.name

class Movie(models.Model):
    adult = models.TextField()
    budget = models.TextField()
    genres = models.TextField()
    original_title = models.TextField()
    overview = models.TextField() # description
    popularity = models.TextField() # audience
    poster_path = models.TextField() # post_url
    release_date = models.TextField()
    revenue = models.TextField()
    runtime = models.TextField()
    tagline = models.TextField()
    title = models.CharField(max_length=150)
    vote_average = models.FloatField()
    actor_1 = models.TextField()
    actor_2 = models.TextField()
    actor_3 = models.TextField()
    actor_4 = models.TextField()
    actor_5 = models.TextField()
    director = models.CharField(max_length=45)
    file_path_1 = models.TextField()
    file_path_2 = models.TextField()
    file_path_3 = models.TextField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_movies")

    def __str__(self):
        return self.title

class Actor(models.Model):
    actor_id = models.TextField()
    actor_name = models.TextField()

    def __str__(self):
        return self.actor_name


class Rating(models.Model): # Review
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    comment = models.TextField()
    score = models.IntegerField(default=1,
                validators=[
                    MaxValueValidator(10),
                    MinValueValidator(1)
            ])

            
    def __str__(self):
        return self.comment

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

from django.views.decorators.http import require_POST

from .forms import CustomUserChangeForm, CustomUserCreationForm 


# Create your views here.
# def index(request):
#     context = {
#         'users' : get_user_model().objects.all()
#     }
#     return render(request, 'accounts/index.html', context)


def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:movie_index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:movies_index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

@login_required
def detail(request, user_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=user_pk)
    context = {
        'user_profile' : user
    }
    return render(request, 'accounts/detail.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:movies_index')
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect(request.GET.get('next') or 'movies:movies_index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('movies:movies_index')

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:movies_index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:movies_index')
    else:
        form = PasswordChangeForm(request.user) # 반드시 첫번째 인자로 user
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def delete(request, user_pk):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect('movies:movies_index')

@login_required
def follow(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)
    if request.user != user:
        if user in request.user.followers.all():
            request.user.followers.remove(user)
        else:
            request.user.followers.add(user)
    return redirect('accounts:detail', user_pk)

def following(request, user_pk):
    host = get_object_or_404(get_user_model(), pk=user_pk)
    followings = host.followers.all()
    context = {
        'followings': followings,
        'host' : host,
    }
    return render(request, 'accounts/following.html', context)

def follower(request, user_pk):
    host = get_object_or_404(get_user_model(), pk=user_pk)
    followers = host.followings.all()
    context = {
        'followers': followers,
        'host' : host,
    }
    return render(request, 'accounts/follower.html', context)

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>I'm your MovieBuddy</title>
  <!-- css -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.css">
  <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">
  <link rel="stylesheet" href="{% static 'css/app.css'%}">
  <!-- bootstrap -->

  <script src="{% static '/js/jquery.js' %}"></script>
  <script src="{% static '/js/jquery.resize.js' %}"></script>
  <script src="{% static '/js/jquery.waitforimages.js' %}"></script>
  <script src="{% static '/js/modernizr.js' %}"></script>
  <script src="{% static '/js/jquery.carousel-3d.js' %}"></script>
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/d00b3497dc.js" crossorigin="anonymous"></script>
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Do+Hyeon&display=swap" rel="stylesheet">
  <!-- Vue -->
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <!-- Axios -->
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script>
    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.xsrfHeaderName = 'X-CSRFToken';
  </script>
  <style>
    body {
      font-family: 'Do Hyeon', sans-serif;
      margin: 0;
      padding: 0;
      background-image: url('{% static '/movies/background.JPG' %}');
      /* background-repeat: no-repeat; */
      background-size: cover;
    }
    .pp {
      position: absolute;
      margin-left: 31.5vw;

    }
    .favorite-box {
      border: 1px solid;
      padding: 13px;
      color: grey;
      width: 25%;
    }
    /* html, body {
      position: relative;
      height: 100%;
    } */

    .swiper-container {
      width: 100%;
      height: 100%;
    }
    .swiper-slide {
      text-align: center;
      font-size: 18px;
      /* background: #fff; */
      /* Center slide text vertically */
      display: -webkit-box;
      display: -ms-flexbox;
      display: -webkit-flex;
      display: flex;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      -webkit-justify-content: center;
      justify-content: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      -webkit-align-items: center;
      align-items: center;
    }
    footer {
      z-index: 90;
    }
  </style>
  {% block css %}
  {% endblock %}
</head>

<body class="text-light">
  {% include '_navbar.html' %}
  <br><br><br>
  <div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags %}{{ message.tags}}{% endif %}">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div id="app">
      {% block app %}{% endblock %}
    </div>
    {% include '_footer.html' %}
    {% block script %}
    {% endblock %}
  </div>
    <!-- Swiper JS -->
    <script src="https://unpkg.com/swiper/js/swiper.js"></script>
    <script src="https://unpkg.com/swiper/js/swiper.min.js"></script>

    <!-- Initialize Swiper -->
    <script>
      var swiper = new Swiper('.swiper-container', {
        slidesPerView: 3,
        spaceBetween: 30,
        slidesPerGroup: 3,
        loop: true,
        loopFillGroupWithBlank: true,
        pagination: {
          el: '.swiper-pagination',
          clickable: true,
        },
        navigation: {
          nextEl: '.swiper-button-next',
          prevEl: '.swiper-button-prev',
        },
      });
    </script>
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

  {% include '_footer.html' %}
</body>

</html>

accounts/templates/accounts/detail.html
{% extends 'accounts/base.html' %}
{% load humanize %}
{% load static %}
{% load gravatar %}
{% block app %}
<h1 class="text-center">
  {{ user_profile.username }}'s Profile
  {% if user != user_profile %}
    {% if user in user_profile.followings.all %}
    <a href="{% url 'accounts:follow' user_profile.pk %}" class="btn btn-outline-warning">Unfollow</a>
    {% else %}
    <a href="{% url 'accounts:follow' user_profile.pk %}" class="btn btn-warning">Follow</a>
    {% endif %}
    {% endif %}
  </h1>
<div class="jumbotron-fluid text-center mb-2 text-white bg-dark">
    <div class="container">
        <br>
        <p class="lead">팔로잉 : 
        <a href="{% url 'accounts:following' user_profile.pk %}">{{ user_profile.followers.all.count }}</a></p><br>
        <p class="lead">팔로워 : 
        <a href="{% url 'accounts:follower' user_profile.pk %}">{{ user_profile.followings.all.count }}</a></p>
        <hr class="border-white">
        <br>
        
    </div>
</div>
{% if user == user_profile %}
<div class="text-center">
    <a href="{% url 'accounts:update' %}" class="badge badge-info">정보 수정</a>
    <a href="{% url 'accounts:password_change' %}" class="badge badge-warning">비밀번호 변경</a>
</div>
{% endif %}
<hr>
<h3 class="text-center">평점을 남겼던 영화</h3>
<div class="row d-flex justify-content-center">
    {% for rating in user_profile.rating_set.all %}

    <div class="col-xl-2 col-lg-4 col-12">
        <div class="card mb-2 bg-dark" style="width: 300px;">
            <a href="{% url 'movies:detail' rating.movie.pk %}"><img
                    src="https://image.tmdb.org/t/p/w500/{{rating.movie.poster_path}}" class="card-img-top"
                    alt="{{rating.movie.title}}" style="width: 300px; height: 500px;"></a>
            <div class="card-body bg-dark" style="width:300px; height: 150px;">
                <h5 class="card-title">
                    {{ rating.movie.title }}<br>
                </h5>
                <!--<p class="card-text">{{ rating.movie.tagline }}</p>-->
                <footer class="blockquote-footer text-warning">{{ rating }}</footer>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<hr>
<br><br><br><br>
{% endblock %}



    {% for rating in user_profile.rating_set.all %}
    <div class="ml-1 col-xl-2 col-lg-4 col-12">
        <div class="card mb-2 bg-dark" style="width: 250px;">
            <a href="{% url 'movies:detail' rating.movie.pk %}"><img
                    src="https://image.tmdb.org/t/p/w500/{{rating.movie.poster_path}}" class="card-img-top"
                    alt="{{rating.movie.title}}" style="width: 80%; height: 80%; text-align: center;"></a>
            <div class="card-body bg-dark" style="width:180px; height: 150px;">
                <h5 class="card-title">
                    {{ rating.movie.title }}<hr>
                </h5>
                <p class="card-text">{{ rating.movie.tagline }}</p>
                <footer class="blockquote-footer text-info" id="my_rating" style= "overflow: hidden;">{{ rating }}</footer>
            </div>
        </div>
    </div>
    {% endfor %}

accounts/templates/accounts/follower.html
{% extends 'accounts/base.html' %}
{% load humanize %}
{% load static %}
{% load gravatar %}
{% block app %}
<h1 class="text-center">
  {{ host.username }}의 팔로워 목록
  </h1>
<div class="jumbotron-fluid text-center mb-2 text-white bg-dark">
    <div class="container">
        {% for follower in followers %}
            <a href="{% url 'accounts:detail' follower.pk %}"><h1>{{ follower }}</h1></a><br>
        {% endfor %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/following.html
{% extends 'accounts/base.html' %}
{% load humanize %}
{% load static %}
{% load gravatar %}
{% block app %}
<h1 class="text-center">
  {{ host.username }}의 팔로잉 목록
  </h1>
<div class="jumbotron-fluid text-center mb-2 text-white bg-dark">
    <div class="container">
        {% for following in followings %}
            <a href="{% url 'accounts:detail' following.pk %}"><h1>{{ following }}</h1></a><br>
        {% endfor %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/form.html
{% extends 'accounts/base.html'%}
{% load bootstrap4 %}

{% block app %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-warning">확인</button>
  {% endbuttons %}
</form>

{% endblock %}