accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('', views.index, name="index"),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('password/', views.password_change, name='password_change'),
    path('<int:user_pk>/', views.detail, name='detail'),    # 프로필
    path('<int:user_pk>/delete/', views.delete, name='delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/following/', views.following, name='following'),
    path('<int:user_pk>/follower/', views.follower, name='follower'),

]

moviebuddy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movies_index, name='movies_index'),
    path('genres/', views.genres_index, name="genres_index"),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('<int:movie_pk>/ratings/<int:rating_pk>/update/', views.rating_update, name='rating_update'),
    path('<int:movie_pk>/ratings/<int:rating_pk>/delete/', views.rating_delete, name='rating_delete'),
    path('<int:movie_pk>/ratings/new/', views.create_rating, name='create_rating'),
    path('myfavorite/', views.myfavorite, name='myfavorite'),
    path('genres/', views.genres_list, name='genres_list'),
    path('actors/', views.actors_list),
    path('api/genres/', views.genres_list, name="genres_list"),
    path('api/genres/<int:pk>/', views.genres_detail, name="genres_detail"),
    path('api/movies/<int:pk>/', views.movies_detail, name="movies_detail"),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings', blank=True)
    

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

from django.views.decorators.http import require_POST

from .forms import CustomUserChangeForm, CustomUserCreationForm 


# Create your views here.
# def index(request):
#     context = {
#         'users' : get_user_model().objects.all()
#     }
#     return render(request, 'accounts/index.html', context)


def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:movie_index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:movies_index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

@login_required
def detail(request, user_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=user_pk)
    context = {
        'user_profile' : user
    }
    return render(request, 'accounts/detail.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:movies_index')
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect(request.GET.get('next') or 'movies:movies_index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('movies:movies_index')

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:movies_index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:movies_index')
    else:
        form = PasswordChangeForm(request.user) # 반드시 첫번째 인자로 user
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def delete(request, user_pk):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect('movies:movies_index')

@login_required
def follow(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)
    if request.user != user:
        if user in request.user.followers.all():
            request.user.followers.remove(user)
        else:
            request.user.followers.add(user)
    return redirect('accounts:detail', user_pk)

def following(request, user_pk):
    host = get_object_or_404(get_user_model(), pk=user_pk)
    followings = host.followers.all()
    context = {
        'followings': followings,
        'host' : host,
    }
    return render(request, 'accounts/following.html', context)

def follower(request, user_pk):
    host = get_object_or_404(get_user_model(), pk=user_pk)
    followers = host.followings.all()
    context = {
        'followers': followers,
        'host' : host,
    }
    return render(request, 'accounts/follower.html', context)

accounts/templates/_footer.html
<footer class="footer mt-5 py-2 text-muted bg-dark" style="position: fixed; bottom: 0; width: 100%; height: 7.5%;">
  <div class="container">
    <p class="float-right">
      <a href="#" style="color: white; font-family: 'Do Hyeon', sans-serif;" >Top</a>
    </p>
    <p style="font-family: 'Do Hyeon', sans-serif;">본 콘텐츠의 저작권은 저작권자 또는 제공처에 있으며, 이를 무단 이용하는 경우 저작권법 등에 따라 법적 책임을 질 수 있습니다.</p>
    <span><p class="float-right" style="font-family: 'Do Hyeon', sans-serif;"> MovieBuddy made by 이지민 & 김은정 </p></span>
  </div>
</footer>

accounts/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'movies:movies_index' %}">MovieBuddy</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!-- 로그인이 되어 있다면, -->
      {% if user.is_authenticated %}
      <!-- 로그인이 되어 있는지 확인하는 method -->

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{user.username}}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:detail' user.pk %}">프로필</a>
            <a class="dropdown-item" href="{% url 'accounts:update' %}">회원정보 수정</a>
            <a class="dropdown-item" href="{% url 'accounts:password_change' %}">비밀번호 변경</a>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">로그아웃</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:delete' user.pk %}">회원탈퇴</a>
          </div>
        </li>
          <li class="nav-item">
                  <a class="nav-link" href="{% url 'movies:myfavorite' %}" tabindex="-1">내가 찜한 영화</a>       
            </li>

        <!-- 로그인이 되어 있지 않다면, -->
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}"> 회원가입</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}"> 로그인</a>
        </li>
      {% endif %}
    </ul>

    <form action="{% url 'movies:movies_index' %}" class="form-inline my-2 my-lg-0 pp">
      <input class="form-control mr-sm-2" type="text" name="keyword" placeholder="영화 제목 검색" aria-label="Search" style="width:350px">
      <button class="btn btn-outline-ligth my-2 my-sm-0" type="submit">Search</button>
    </form>
    <div id="spin-container">
        <video controls autoplay="autoplay" style="display: none;">
        </video>
      </div>
    <div id="ground" style="height: 3px;"></div>
    <div id="music-container" style="height: 30;"></div>
    &nbsp;
  </div>

</nav>